---
- name: Configure photomaton
  hosts: all
  become: true
  tasks:
    - name: Import install_photobooth tasks
      ansible.builtin.import_tasks: tasks/install_photobooth.yml
      tags: install
    - name: Import configure_photobooth tasks
      ansible.builtin.import_tasks: tasks/configure_photobooth.yml
      tags: config
