---
- name: Ensure custom photobooth configuration is installed
  ansible.builtin.template:
    dest: /var/www/html/config/my.config.inc.php
    src: my.config.inc.php.j2
    owner: www-data
    group: www-data
    mode: "0660"
  tags: config

- name: Copy private files
  ansible.builtin.copy:
    dest: "/var/www/html/private/"
    src: "private/"
    owner: www-data
    group: www-data
  tags: config
