---
- name: Get gupload
  become: true
  ansible.builtin.get_url:
    url: https://github.com/labbots/google-drive-upload/raw/master/install.sh
    dest: /tmp/install.sh
    mode: 0770

- name: Install gupload
  become: true
  ansible.builtin.command:
    cmd: "/tmp/install.sh -p /usr/bin"
  register: gupload_output
  changed_when: gupload_output.rc != 0

