---
- name: Get latest installation script version
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/PhotoboothProject/photobooth/dev/install-photobooth.sh"
    dest: /tmp/install-photobooth.sh
    mode: "0777"

- name: Execute installation script
  changed_when: true
  ansible.builtin.command:
    argv:
      - bash
      - /tmp/install-photobooth.sh
      - -username=photobooth
      - -s
